include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
